global using Blazored.LocalStorage;
global using System.Net.Http.Headers;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Components.Authorization;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.IdentityModel.Tokens;
global using System.Text;
global using System.Text.Json;
global using System.Security.Claims;

// Projects Imports
global using Blazor.Domain.Identity;
global using Blazor.Application.Persistence;
global using Blazor.Server.Models;
global using Blazor.RepositoryPattern;
global using Blazor.Server.Auth;
global using Blazor.Application;
global using Blazor.Application.Models;
global using Blazor.Application.Interfaces;
global using Blazor.Domain;
