global using Blazor.Domain.Entities;
global using Blazor.RepositoryPattern.Interfaces;
global using Blazor.RepositoryPattern.Repositories;
global using AutoMapper;
global using Blazor.RepositoryPattern.Models;
global using Blazor.Application.Persistence;
global using Blazor.RepositoryPattern.Services;
global using Microsoft.Extensions.DependencyInjection;
global using Blazor.Domain.Responses;
